# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 03:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='pinglun')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='kecheng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yonghuming')),
            ],
            options={
                'verbose_name': 'kechengpinglun',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='xingming')),
                ('mobile', models.CharField(max_length=11, verbose_name='shouji')),
                ('course_name', models.CharField(max_length=50, verbose_name='kechengming')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
            ],
            options={
                'verbose_name': 'yonghuzixun',
                'verbose_name_plural': 'yonghuzixun',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='kecheng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yonghuming')),
            ],
            options={
                'verbose_name': 'yonghukecheng',
                'verbose_name_plural': 'yonghukecheng',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='shujuid')),
                ('fav_type', models.IntegerField(choices=[(1, 'kecheng'), (2, 'kechengjigou'), (3, 'jiangshi')], default=1, verbose_name='shoucangleixing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yonghuming')),
            ],
            options={
                'verbose_name': 'yonghushoucang',
                'verbose_name_plural': 'yonghushoucang',
            },
        ),
        migrations.CreateModel(
            name='UserMesaage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='jieshouyonghu')),
                ('message', models.CharField(max_length=500, verbose_name='xiaoxineirong')),
                ('has_read', models.BooleanField(default=False, verbose_name='shifouyidu')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
            ],
            options={
                'verbose_name': 'yonghuxiaoxi',
                'verbose_name_plural': 'yonghuxiaoxi',
            },
        ),
    ]
