# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kechengming')),
                ('desc', models.CharField(max_length=300, verbose_name='kechengmiaoshu')),
                ('detail', models.TextField(verbose_name='kechengxiangqing')),
                ('degree', models.CharField(choices=[('cj', 'chuji'), ('zj', 'zhongji'), ('gj', 'gaoji')], max_length=50)),
                ('learn_times', models.IntegerField(default=0, verbose_name='xuexishichang(fenzhongshu)')),
                ('students', models.IntegerField(default=0, verbose_name='xuexirenshu')),
                ('fav_num', models.IntegerField(default=0, verbose_name='shoucangrenshu')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='fengmiantu')),
                ('click_num', models.IntegerField(default=0, verbose_name='dianjishu')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
            ],
            options={
                'verbose_name': 'kecheng',
                'verbose_name_plural': 'kecheng',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='mingcheng')),
                ('download', models.FileField(upload_to='course/%Y/%m', verbose_name='ziyuanwenjian')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='kecheng')),
            ],
            options={
                'verbose_name': 'kechengziyuan',
                'verbose_name_plural': 'kechengziyuan',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='zhangjieming')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='kecheng')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='shipinming')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='zhangjie')),
            ],
        ),
    ]
