# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'yonghuxinxi', 'verbose_name_plural': 'yonghuxinxi'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='shengri'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'nan'), ('female', 'nv')], default='female', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='nichen'),
        ),
    ]
