# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171217_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=100, verbose_name='biaoti')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='lunbotu')),
                ('url', models.URLField(verbose_name='fangwendizhi')),
                ('index', models.IntegerField(default=100, verbose_name='shunxu')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='fangwenshijian')),
            ],
            options={
                'verbose_name': 'lunbotu',
                'verbose_name_plural': 'lunbotu',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='yanzhengma')),
                ('email', models.EmailField(max_length=50, verbose_name='youxiang')),
                ('send_type', models.CharField(choices=[('register', 'zhuce'), ('forget', 'zhaohuimima')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'youxiangyanzhengma',
                'verbose_name_plural': 'youxiangyanzhengma',
            },
        ),
    ]
