# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banne_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'nan'), ('female', 'nv')], default='female', max_length=10),
        ),
    ]
